# file: respond.ini

# ====================================================================
# this file is an example discovery profile for use by program respond
# which demonstrates Simple Network Discovery Protocol; the values here
# must conform to the TLVs descriptions in the Simple Network Discovery
# protocol programmers guide;
# --------------------------------------------------------------------

[Standard]
Chassis ID = 04:AA:BB:CC:DD:EE:FF
Port ID = 03:11:22:33:44:55:66
Time To Live = 3600
Port Description = My Port Description
# System Name = My System Name
System Description = My System Description
System Capabilities = FF:FF:12:34
Management URL = http://www.configure.net/configure

[Specific]
Manufacturer = Qualcomm Atheros
Hardware Model = QCA7000
Serial Number = 0123-4567-100
HOST MAC = 11:22:33:44:55:66
PLC MAC = 00:B0:52:00:BA:BE
WIFI MAC = AA:BB:CC:DD:EE:FF
WIFI IP = 00:FF:FF:AB:CD

