.TH respond 1 "Mar 2014" "plc-utils-2.1.6" "Qualcomm Atheros Powerline Toolkit"

.SH NAME
respond - Qualcomm Atheros Network Responder

.SH SYNOPSIS
.BR respond
.RI [ options ] 

.SH DESCRIPTION
Respond to topology requests from powerline network solicitors.
This is a proof-of-concept program that does nothing useful, as it stands.
It is maintained in case there is a need, in the future, to make it do something useful.
It requires one or more instances of program solicit to demonstrate the concept.
The underlying protocol is essentially LLDP.

.PP
This program is part of the Qualcomm Atheros Powerline Toolkit.
See the \fBplc\fR man page for an overview and installation instructions.

.SH OPTIONS

.TP
.RB - i
Select the host Ethernet interface.
All requests are sent via this host interface and only reponses received via this host interface are recognized.
The default interface is \fBeth1\fR because most people use \fBeth0\fR as their principle network connection; however, if environment string "PLC" is defined then it takes precedence over the default interface.
This option then takes precedence over either default.

.TP
-\fBp \fIprofile\fR
The configuration profile name.
The file must have two sections: "\fBStandard\fR" and "\fBSpecific\fR".
Profile elements must conform to the TLV descriptions defined in \fISimple Network Discovery Protocol Programmers Guide\fR.
The program will supply a default value for any omitted configuration profile elements.
See the example profile shown below.
The default filename is "\fBrespond.ini\fR".

.TP
.RB - q
Enter quiet mode.
Progress messages are suppressed.

.TP
.RB - v 
Enter verbose mode.
All Etherenet frames sent or received by the program are displayed on stdout.

.TP
-\fBw \fImilliseconds\fR
Wakeup frequency in milliseconds.
This is the time between announcements.
During this time, the program listens for solicitor rquests.
Values range from 0 through UINT_MAX.
'
The default is forever.
.TP
-\fB?\fR, --\fBhelp\fR
Print program help summary on stdout. This option takes precedence over other options on the command line. 
.TP
-\fB!\fR, --\fBversion\fR
Print program version information on stdout. This option takes precedence over other options on the command line. Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.
.SH REFERENCES
See the Qualcomm Atheros Simple Network Discovery Protocol for more information about \fBsolicitors\fR, \fBresponders\fR and \fBTLVs\fR.
.SH EXAMPLES
The following command starts a responder on the local host. The responder will announce and listen on interface \fBeth0\fR. The responder will announce values defined in profile "\fBrespond.ini\fR" by default because option \fB-p\fR is absent.
.PP
   # respond -i eth0
.PP
An example profile, "\fBrespond.ini\fR", looks something like this. This configuration file is provided for demonstration purposes only. The source code that parses this file does not support all possible variations these configuration values. See \fIIEEE Standard for Local and metworpolitan networks - Station and Meida Access Control Connectivity Discovery\fR for an explanation of the the value
.PP
   # file: respond.ini
 
   # ====================================================================
   # This is an example profile for use by program respond; it supports 
   # the Qualcomm Atheros Simple Network Discovery protocol;
   # --------------------------------------------------------------------
   
   [Standard]
   Chassis ID = 04AABBCCDDEEFF
   Port ID = 03112233445566
   Time To Live = 3600 
   Port Description = The Internet of Things
   System Name = WNC Hybrid Router
   System Description = Shanghai Public Library Wireless Network
   System Capabilities = 00:FF:FF:FF:FF
   Management Address = http://www.mamagement.com
   
   [Specific]
   Manufacturer = Qualcomm Atheros
   Hardware Model = QCA7000
   Serial Number = QCA7000-ND25B-0003
   HOST MAC = 88:77:66:55:44:33
   PLC MAC = 00:B0:52:00:BA:BE
   WIFI MAC = AA:BB:CC:DD:EE:FF
   WIFI IP = 00:FF:FF:AB:CD
   
.SH SEE ALSO
.BR plc ( 1 ),
.BR solicit ( 1 ),
.SH CREDITS
 Charles Maier <cmaier@qca.qualcomm.com>
'

