# file: solicit.ini

# ====================================================================
# this file is an example discovery profile for use by program solicit
# which demonstrates Simple Network Discovery Protocol; the profile is
# empty because program solicit does not require special parameters;
# --------------------------------------------------------------------

 [default]

