#include "fapi_sys_common.h"
/* Initialize callback hanlders for xRX330 platform */
static SysFapiCB_t fapicb={
	.flag=2,
	.wanSWO = XRX330_wanSWO,
	.moduleLoad = xRX330_module_load,
	.moduleUnLoad = xRX330_module_unload,
	.ProcessorInit = Processor_init,
	.ProcessorUnInit = Processor_uninit,
	.ProcessorStat = stats_counter,
	.SysInit = xRX330_module_init,
	.SysUnInit = xRX330_module_uninit,
	.ppa_init = PPAInit,
	.ppa_uninit = PPAUnInit,
	.sysSet = SysSet,
	.sysGet = SysGet,
	.ppaAdd = PPAIntfAdd,
	.ppaDel = PPAIntfDel,
	.ppaHook = PPAEnHook,
	.VLANCfgSet = xRX330_VLANCfgSet,
	.RMONGet = RMONGet,
	.getPortId = xRX330_PortIdGet,
	.setPortStatus = SetPortStatus,
	.getPortStatus = xRX330_GetPortStatus,
	.setMaxRate = SetMaxBitRate,
	.getMaxRate = GetMaxBitRate,
	.setDuplexMode = SetDuplexMode,
	.getDuplexMode = GetDuplexMode,
	.GetLinkState = GetLinkState,
	.SetLinkState = SetLinkState,  
	.EnMirror = EnableMirroring,
	.disMirror = DisableMirroring, 
	.cfgbrAccel= xRX330_CfgBridgeAccel,
	.cfg_SwitchIOCTL = xRX330_cfg_SwitchIOCTL,
	.setInterfaceState = xRX330_SetInterface,
	.setBridgeState = xRX330_SetBridgeAcclState,
	.setWanPhyGpio = xRX330_SetWanPhyGpio,
};

