#include "fapi_sys_common.h"
/* Initialize callback hanlders for xRX220 platform */
static SysFapiCB_t fapicb={
	.flag=2,
	.wanSWO = XRX220_wanSWO,
	.moduleLoad = xRX220_module_load,
	.moduleUnLoad = xRX220_module_unload,
	.ProcessorInit = Processor_init,
	.ProcessorUnInit = Processor_uninit,
	.ProcessorStat = stats_counter,
	.SysInit = xRX220_module_init,
	.SysUnInit = xRX220_module_uninit,
	.ppa_init = PPAInit,
	.ppa_uninit = PPAUnInit,
	.sysSet = SysSet,
	.sysGet = SysGet,
	.ppaAdd = PPAIntfAdd,
	.ppaDel = PPAIntfDel,
	.ppaHook = PPAEnHook,
	.VLANCfgSet = xRX220_VLANCfgSet,
	.RMONGet = RMONGet,
	.getPortId = xRX220_PortIdGet,
	.setbrCfg = xRX220_setBrCfg,
	.setPortStatus = SetPortStatus,
	.getPortStatus = xRX220_GetPortStatus,
	.setMaxRate = SetMaxBitRate,
	.getMaxRate = GetMaxBitRate,
	.setDuplexMode = SetDuplexMode,
	.getDuplexMode = GetDuplexMode,
	.GetLinkState = GetLinkState,
	.SetLinkState = SetLinkState,  
	.EnMirror = xRX220_EnableMirroring,
	.disMirror = xRX220_DisableMirroring, 
	.cfgbrAccel= xRX220_CfgBridgeAccel,
	.cfg_SwitchIOCTL = xRX220_cfg_SwitchIOCTL,
};

