# Preserved from the C-Life-XG1 branch.
export RT-AX53U := IPV6SUPP=y SYSCLASSGPIO=y HTTPS=y MIPS32=r2 RALINK=y MT7621=y BBEXTRAS=y EBTABLES=y USBEXTRAS=y SAMBA4=y MEDIASRV=y MEDIASRV_LIMIT=y PARENTAL2=y USB="USB" APP="installed" AUTODICT=y SHP=y RTAX53U=y MUSL_LIBC=y XHCI=n ODMPID=y LED_ALL=y NEW_RGDM=y RA_SKU_IN_DRV=y TCODE=y MDNS=y FINDASUS=y SSH=y LAN50=y ATCOVER=y NEWSSID_REV4=y UTF8_SSID=y NO_SELECT_CHANNEL=y NATNL_AIHOME=y FRS_FEEDBACK=y NO_FTP_SSL=y \
	LANWAN_LED=y BTN_WPS_ALLLED=y \
	BOOT_FLASH_TYPE=SPI MTK_NAND=y MTK_NAND_BLOCK2=y DUAL_TRX=y NVRAM_ENCRYPT=y USB_SWAP=y OPENVPN=y ACCEL_PPTPD=y VPNC=y NTFS="open_2016" EXT4FS=y REBOOT_SCHEDULE=y HD_SPINDOWN=y \
	DRAM=256M \
	MTK_8021XD3000=y \
	EDCCA_NEW=y \
	FIRST_IF=MT7915D SECOND_IF=MT7915D \
	RALINK_DFS=y MTK_MUMIMO=y MUMIMO_5G=y MUMIMO_2G=y QAM256_2G=y QAM1024_5G=y REPEATER=y PROXYSTA=y SW_HW_AUTH=y ATF=y SAVE_WL_NVRAM_BOTH=y CAPTCHA=y RALINK_BUILDIN_WIFI=y \
	JFFS2=y PSISTLOG=y \
	TEMPROOTFS=y \
	FORCE_AUTO_UPGRADE=n ALEXA=y DUALWAN=y LETSENCRYPT=y BWDPI=y IPSEC=STRONGSWAN IPSEC_SRVCLI_ONLY=SRV INSTANT_GUARD=y FRS_LIVE_UPDATE=y ASUSCTRL=y MULTICASTIPTV=y QUAGGA=y PMF=y VPN_FUSION=n \
	DTB="mt7621-rfb-ax-nmbm.dtb" \
	EXTRA_KERNEL_CONFIGS="MT7621_BAUDRATE=115200 UBOOT_CMDLINE=y MODEL_RTAX53U=y DUAL_TRX=y" \
	INTERNETCTRL=y MODEM=y GOOGLE_ASST=y AUTO_FW_UPGRADE=y PRINTER=y AMAS=y NEW_USER_LOW_RSSI=y MSSID_PRELINK=y AVBLCHAN=y IPV6S46=y OCNVC=y ECC256=y SW_CTRL_ALLLED=y MTK_BSD=y USB_WAN_BACKUP=y
export RT-AX53U += BUILD_NAME="RT-AX53U" REAL_NAME="XG1" GAME_MODE=y OPEN_NAT=y
export RT-AX53U += TR069=y ISP_CUSTOMIZE=y
export RT-AX53U += BOARD_C_LIFE_XG1=y
