#!/bin/sh

# autobuildall [type] [model] [branch] [commit] [repository] [log extension]

LOGDIR="asuswrt.log"
LOGPATH="./${LOGDIR}/"
CURRENTPATH=`pwd`

export ASUSWRTDIR="asuswrt-repository-$5"
export ASUSWRTVERSIONCONFDIR="$CURRENTPATH/${LOGDIR}/${ASUSWRTDIR}"
export ASUSWRTTARGETMAKDIR="$CURRENTPATH/${LOGDIR}/${ASUSWRTDIR}"

export ASUSWRTRELEASEDIR="/mnt/tp-fs-11/ASUSWRT/Firmware_SQ"
export ASUSWRTBACKUPDIR="/mnt/sharing-new/Projects/ASUSWRT"
export LOCALRELEASEDIR="/samba/share/gitserv_asus/FW"

TOOLPATH="./${ASUSWRTDIR}/buildtools"
BUILDPATH="./${ASUSWRTDIR}/release/src-rt"

echo "STARTING" > $LOGPATH/${ASUSWRTDIR}/autobuildalltag
rm -f $LOGPATH/${ASUSWRTDIR}/autobuild_errlog
rm -f $LOGPATH/${ASUSWRTDIR}/autobuild_oversizelog

trap "echo STOPPED > $LOGPATH/${ASUSWRTDIR}/autobuildalltag;exit" TERM


# switch to correct status

# prepare correct autologin.exp: pull correct tag
cat ${TOOLPATH}/autologin.exp | sed s/\$branch/${3}/ > ./autologin-$5.exp ; chmod +x ./autologin-$5.exp

if [ "$3" = "$4" ]; then
	cd ${ASUSWRTDIR} && ../git-clean.sh && ../autologin-$5.exp ; git checkout $3 && cd ..

	rm -rf ./autologin-$5.exp
else
 	cd ${ASUSWRTDIR} && ../git-clean.sh && git checkout $4 ; cd ..
fi

rm -rf ./autologin-$5.exp

echo `pwd`
# build current 
if [ $1 != "BETAFW" ] && [ $1 != "BETAGPL" ]; then
	cp $BUILDPATH/version.conf $LOGPATH/${ASUSWRTDIR}/. -f
else
	cat $BUILDPATH/version.conf | sed -e 's/KERNEL_VER=3.0/KERNEL_VER=9.0/' > $LOGPATH/${ASUSWRTDIR}/version.conf
fi

cp $TOOLPATH/target.mak.3004 $LOGPATH/${ASUSWRTDIR}/target.mak -f

if [ $1 != "GPL" ] && [ $1 != "BETAGPL" ]; then
	FLAG="tag"
else
	FLAG="gpl"
fi

# prepare correct autologin.exp: pull the latest tag and update release note only when building the latest commit 
if [ "$3" = "$4" ]; then
	echo "1"
	cat $TOOLPATH/autologin.exp | sed s/xpdev\ \$branch/origin\ --tags/ > ./autologin-$5.exp ; chmod +x ./autologin-$5.exp
	cd ${ASUSWRTDIR} && ../autologin-$5.exp ; cd ..
	rm -rf ./autologin-$5.exp

	echo "2"
	# update change log here
	. $LOGPATH/${ASUSWRTDIR}/version.conf	

	cd ${ASUSWRTDIR} && echo "`date '+%Y%m%d'`- ${KERNEL_VER}.${FS_VER} build ${SERIALNO} extend no `git log --pretty=oneline asuswrt_${KERNEL_VER}.${FS_VER}.${SERIALNO}..HEAD | wc -l`-g`git log --pretty=format:'%h' -n 1`" > ../newlog && (git log --pretty="%s - [%h], %an, %ad" asuswrt_${KERNEL_VER}.${FS_VER}.${SERIALNO}_latest..HEAD | sed 's/^/	/' | grep -v "Merge" >> ../newlog || true) && echo "\n" >> ../newlog && echo "EXTENDNO=`git log --pretty=oneline asuswrt_${KERNEL_VER}.${FS_VER}.${SERIALNO}..HEAD | wc -l`" > ../$LOGPATH/${ASUSWRTDIR}/extendno && cd ..

	echo "3"
	rm -rf ./nvramlog
	cd ${ASUSWRTDIR} && git diff asuswrt_${KERNEL_VER}.${FS_VER}.${SERIALNO}_latest..HEAD release/src/router/shared/defaults.c >> ../nvramlog && cd ..
	rm -rf ./difflog
	#cd ${ASUSWRTDIR} && git diff asuswrt_${KERNEL_VER}.${FS_VER}.${SERIALNO}_latest..HEAD | buildtools/parsediff.sh >> ../difflog && cd ..
fi

echo "4"
if [ "$2" != "MODELS" ]; then
	MODELS=`echo "$2" | sed s/,/\ /g`
else
	MODELS="rt-ac68u rt-ac86u"
fi

. $LOGPATH/${ASUSWRTDIR}/extendno

echo "5"
if [ ! -f $LOGPATH/log/autobuild_log_${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO} ] || [ "$3" != "$4" ]; then

	for model in $MODELS
	do
		umodel=`echo $model | tr '[:lower:]' '[:upper:]'`
		/media/ASUSWRT/autobuild $FLAG $model
		/media/ASUSWRT/scripts/parseconfig.sh ${ASUSWRTDIR} ${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO} ${LOGPATH} ${umodel}
	done

	touch $LOGPATH/log/autobuild_log_${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO}

	if [ "$3" = "$4" ]; then
		cat $TOOLPATH/autologin.exp | sed s/pull\ xpdev\ \$branch/push\ --tags/ > ./autologin-$5.exp ; chmod +x ./autologin-$5.exp
		cd ${ASUSWRTDIR} && ../autologin-$5.exp ; cd ..
		rm -rf ./autologin-$5.exp

		if [ "$FLAG" != "gpl" ]; then
			NVRAMCHANGED=`stat --printf="%s" nvramlog`
			DIFFCHANGED=`stat --printf="%s" difflog`
			if [ "$NVRAMCHANGED" != "0" ]; then
				echo "\n\tDefault vlaue changed in this build:" >> newlog
				cat nvramlog | grep "+\|-" | sed -e 's/^/\t/' >> newlog
			fi
			if [ -f $LOGPATH/${ASUSWRTDIR}/autobuild_errlog ]; then
				echo "\n\tModels missed in this build:" >> newlog
				cat $LOGPATH/${ASUSWRTDIR}/autobuild_errlog | sed -e 's/^/\t/' >> newlog
			fi
			echo "\n" >> newlog
			if [ -f $LOGPATH/${ASUSWRTDIR}/autobuild_oversizelog ]; then
				echo "\n\tModels fw oversized in this build:" >> newlog
				cat $LOGPATH/${ASUSWRTDIR}/autobuild_oversizelog | sed -e 's/^/\t/' >> newlog
			fi
			echo "\n" >> newlog

			if [ "$DIFFCHANGED" != "0" ]; then
				echo "\n\tDiff and related dependence in this build:" >> newlog
				cat difflog | sed -e 's/^/\t/' >> newlog
			fi
			echo "\n" >> newlog

			cp changelog.${KERNEL_VER}.${FS_VER}.${SERIALNO} change.log -f
			cat change.log | tr -d '\r' >> newlog && mv -f newlog changelog.${KERNEL_VER}.${FS_VER}.${SERIALNO}
			cp changelog.${KERNEL_VER}.${FS_VER}.${SERIALNO} ${ASUSWRTRELEASEDIR}/. -f
			cp changelog.${KERNEL_VER}.${FS_VER}.${SERIALNO} ${ASUSWRTBACKUPDIR}/. -f

			CSVREPORT="`date '+%Y%m%d-%H%M%S'`-autobuild-${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO}.csv"
			echo "ModelName,FW,FW ExtendNo,Pass/Fail,OverSize" > $CSVREPORT
			for model in $MODELS
			do
				umodel=`echo $model | tr '[:lower:]' '[:upper:]'`
				FOUNDERR=`cat $LOGPATH/${ASUSWRTDIR}/autobuild_errlog | grep $umodel`
				cp $LOGPATH/${ASUSWRTDIR}/autobuild_errlog $LOGPATH/misc/autobuild_errlog_$umodel_${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO}
				if [ "$FOUNDERR" = "" ]; then
					BUILDRET="pass"
				else
					BUILDRET="fail"
				fi
				FOUNDERR=`cat $LOGPATH/${ASUSWRTDIR}/autobuild_oversizelog | grep $umodel`
				cp $LOGPATH/${ASUSWRTDIR}/autobuild_oversizelog $LOGPATH/misc/autobuild_oversizelog_$umodel_${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO}
				if [ "$FOUNDERR" = "" ]; then
					BUILDOVER="pass"
				else
					BUILDOVER="fail"
				fi
				echo "$model,${KERNEL_VER}.${FS_VER}.${SERIALNO},${EXTENDNO},$BUILDRET,$BUILDOVER" >> $CSVREPORT
			done

			cp $CSVREPORT ${ASUSWRTRELEASEDIR}/CI-REPORT/. -f
			cp $CSVREPORT ${ASUSWRTBACKUPDIR}/CI-REPORT/. -f
			cp $LOGPATH/log/*${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO}* ${ASUSWRTRELEASEDIR}/CI-REPORT/config/. -f
			cp $LOGPATH/log/*${KERNEL_VER}.${FS_VER}.${SERIALNO}.${EXTENDNO}* ${ASUSWRTBACKUPDIR}/CI-REPORT/config/. -f
		fi # end if of flag
	fi
fi

cd $TOOLPATH && git reset --hard HEAD && cd ../..

echo "STOPPED" > $LOGPATH/${ASUSWRTDIR}/autobuildalltag
