#!/bin/bash
file1=$1
file2=$2
tmpfile1="/tmp/targetdiff1.$$.tmp"
makfile1="/tmp/targetdiff1.$$.mak"
tmpfile2="/tmp/targetdiff2.$$.tmp"
makfile2="/tmp/targetdiff2.$$.mak"

if [ -z "$file1" -o -z "$file2" ]; then
	echo "Usage: $0 target.mak.orig target.mak.new"
	exit 1
fi

echo "--- $file1"
echo "+++ $file2"

models=$(awk '/export/ { print $2; }' $file1 $file2 | sort -u)
for model in $models; do
	echo -e "include $file1\nall:\n\techo \$($model)" > $makfile1
	for option in $(make -s -f $makfile1); do
		echo $option
	done | sort -u > $tmpfile1
	echo -e "include $file2\nall:\n\techo \$($model)" > $makfile2
	for option in $(make -s -f $makfile2); do
		echo $option
	done | sort -u > $tmpfile2
	diff=$(diff -U0 $tmpfile1 $tmpfile2 | sed '/^[^-+]\|^[-+]\{2,\}/d')
	[ -z "$diff" ] && continue
	echo "@@ $model @@"
	echo "$diff"
done

rm $tmpfile1 $makfile1
rm $tmpfile2 $makfile2
