/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux fd69b6f2cff8 6.8.0-137-generic #137-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul 17 20:28:23 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Thu Sep 17 13:54:56 CST 2026"
#define BUILD_ENV_SRCDIR "/repo/Fail_GPL/asuswrt/release/src/router/samba-4.0.24/source/source3"
#define BUILD_ENV_BUILDDIR "/repo/Fail_GPL/asuswrt/release/src/router/samba-4.0.24/source/source3"
#define BUILD_ENV_USER "asuswrt"
#define BUILD_ENV_HOST "fd69b6f2cff8"
#define BUILD_ENV_COMPILER "/opt/lede-toolchain-ramips-mt7621_gcc-5.4.0_musl-1.1.24.Linux-x86_64/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.24/bin/mipsel-openwrt-linux-musl-gcc"
#endif /* _BUILD_ENV_H */
