/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux 820a0eb7ac91 6.8.0-137-generic #137-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul 17 20:28:23 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Wed Sep 16 17:56:17 CST 2026"
#define BUILD_ENV_SRCDIR "/repo/Pass_GPL/asuswrt/release/src/router/samba-4.0.24/source/source3"
#define BUILD_ENV_BUILDDIR "/repo/Pass_GPL/asuswrt/release/src/router/samba-4.0.24/source/source3"
#define BUILD_ENV_USER "asuswrt"
#define BUILD_ENV_HOST "820a0eb7ac91"
#define BUILD_ENV_COMPILER "/opt/lede-toolchain-ramips-mt7621_gcc-5.4.0_musl-1.1.24.Linux-x86_64/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.24/bin/mipsel-openwrt-linux-musl-gcc"
#endif /* _BUILD_ENV_H */
