/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-mipsel"
#define DATE "built on: Thu Sep 17 02:03:34 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','o','p','t','/','l',
    'e','d','e','-','t','o','o','l','c','h','a','i','n','-','r','a',
    'm','i','p','s','-','m','t','7','6','2','1','_','g','c','c','-',
    '5','.','4','.','0','_','m','u','s','l','-','1','.','1','.','2',
    '4','.','L','i','n','u','x','-','x','8','6','_','6','4','/','t',
    'o','o','l','c','h','a','i','n','-','m','i','p','s','e','l','_',
    '2','4','k','c','_','g','c','c','-','5','.','4','.','0','_','m',
    'u','s','l','-','1','.','1','.','2','4','/','b','i','n','/','m',
    'i','p','s','e','l','-','o','p','e','n','w','r','t','-','l','i',
    'n','u','x','-','m','u','s','l','-','g','c','c',' ','-','f','P',
    'I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','a','b',
    'i','=','3','2',' ','-','W','a',',','-','-','n','o','e','x','e',
    'c','s','t','a','c','k',' ','-','D','R','T','A','X','5','3','U',
    ' ','-','D','R','T','A','X','5','3','U',' ','-','D','M','U','S',
    'L','_','L','I','B','C',' ','-','D','R','T','A','X','5','3','U',
    ' ','-','D','B','C','M','_','E','V','E','N','T','D',' ','-','D',
    'E','X','T','_','A','C','S',' ','-','D','_','_','C','O','N','F',
    'I','G','_','E','M','F','_','_',' ','-','D','_','_','C','O','N',
    'F','I','G','_','W','P','S','_','_',' ','-','O','2',' ','-','f',
    'f','u','n','c','t','i','o','n','-','s','e','c','t','i','o','n',
    's',' ','-','f','d','a','t','a','-','s','e','c','t','i','o','n',
    's',' ','-','D','O','P','E','N','S','S','L','_','U','S','E','_',
    'N','O','D','E','L','E','T','E',' ','-','D','L','_','E','N','D',
    'I','A','N',' ','-','D','O','P','E','N','S','S','L','_','P','I',
    'C',' ','-','D','O','P','E','N','S','S','L','_','B','N','_','A',
    'S','M','_','M','O','N','T',' ','-','D','S','H','A','1','_','A',
    'S','M',' ','-','D','S','H','A','2','5','6','_','A','S','M',' ',
    '-','D','A','E','S','_','A','S','M',' ','-','D','_','X','O','P',
    'E','N','_','S','O','U','R','C','E','=','5','0','0',' ','-','D',
    'N','D','E','B','U','G',' ','-','D','O','P','E','N','S','S','L',
    '_','A','P','I','_','C','O','M','P','A','T','=','0','x','1','0',
    '0','0','0','0','0','0','L',' ','-','D','O','P','E','N','S','S',
    'L','_','P','R','E','F','E','R','_','C','H','A','C','H','A','_',
    'O','V','E','R','_','G','C','M','\0'
};
