# ====================================================================
# programs;
# --------------------------------------------------------------------

add_executable(config2cfg config2cfg.c)
add_executable(sdram sdram.c)

# ====================================================================
# dependencies;
# --------------------------------------------------------------------

target_link_libraries(config2cfg tools)
target_link_libraries(sdram tools)

# ====================================================================
# libraries;
# --------------------------------------------------------------------

add_library(ram sdrampeek.c nvram.c sdramfile.c)

