#***********************************************************************
#
# Makefile
#
#***********************************************************************

all:
	-cp prebuild/$(PREBUILT_NAME)/inotify inotify

.PHONY: clean
clean:
	-rm -rf *.o inotify
