.TH plcnets 1 "Mar 2014" "plc-utils-2.1.6" "Qualcomm Atheros Powerline Toolkit"

.SH NAME
plcnets - Qualcomm Atheros Powerline Network Enumerator

.SH SYNOPSIS
.BR plcnets
.RI [ options ]

.SH DESCRIPTION
Search host Ethernet interfaces for Atheros powerline networks.

.SH COMMENTS
This program illustrates use of some basic Atheros powerline networking classes.

.SH OPTIONS

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Intellon Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH ARGUMENTS
None.

.SH EXAMPLES
The following example searches host Ethernet interfaces for powerline network devices on a \fBWindows\fR host.

.PP
   # plcnets 
   Search interface \fBnic2\fR for powerline devices ...
   P/L NET TEI ------ MAC ------ ------ BDA ------  TX  RX CHIPSET FIRMWARE
   LOC STA 002 00:B0:52:DA:DA:3B 00:0E:2E:03:5F:B8 000 000 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B
   REM CCO 001 00:B0:52:BE:EF:52 00:19:D1:25:51:32 143 145 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B
   Search interface \fBnic3\fR for powerline devices ...
   Search interface \fBnic4\fR for powerline devices ...
   P/L NET TEI ------ MAC ------ ------ BDA ------  TX  RX CHIPSET FIRMWARE
   LOC CCO 001 00:B0:52:BE:EF:52 00:0C:76:87:3E:3D 000 000 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B
   REM STA 002 00:B0:52:DA:DA:3B 00:0E:2E:03:5F:B8 145 143 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B

.PP
The following example searches host Ethernet interfaces for powerline network devices on a \fBLinux\fR host.

.PP
   # plcnets 
   Search interface \fBeth4\fR for powerline devices ...
   Search interface \fBeth3\fR for powerline devices ...
   P/L NET TEI ------ MAC ------ ------ BDA ------  TX  RX CHIPSET FIRMWARE
   LOC CCO 001 00:B0:52:BE:EF:52 00:0F:EA:4B:98:CB 000 000 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B
   REM STA 002 00:B0:52:DA:DA:3B 00:0E:2E:03:5F:B8 141 132 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B

.PP
The following example searches host Ethernet interfaces for powerline network devices on a \fBMacOSX\fR host.

.PP
   # plcnets 
   Search interface \fBen0\fR for powerline devices ...
   P/L NET TEI ------ MAC ------ ------ BDA ------  TX  RX CHIPSET FIRMWARE
   LOC CCO 001 00:B0:52:BE:EF:52 00:26:BB:52:DD:A8 000 000 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B
   REM STA 002 00:B0:52:DA:DA:3B 00:0E:2E:03:5F:B8 141 132 INT6300 INT6000-MAC-4-1-4122-00-4014-20091028-FINAL-B
   Search interface \fBfw0\fR for powerline devices ...
   Search interface \fBen1\fR for powerline devices ...

.SH SEE ALSO
.BR amp ( 1 ),
.BR ifs ( 1 ),
.BR nics ( 1 ),
.BR pcapdevs ( 1 )

.SH CREDITS 
 Charles Maier <cmaier@qca.qualcomm.com>

