# generated by ./configure on Thu Sep 17 11:56:28 CST 2026
SRCDIR = .
CPPFLAGS += -I.
CPPFLAGS += -I/repo/Pass_GPL/asuswrt/release/src-ra-openwrt-4210/router/iptables-1.4.x/include/
LDFLAGS += -L/repo/Pass_GPL/asuswrt/release/src-ra-openwrt-4210/router/iptables-1.4.x/libiptc/
# detected libiptc version 1.4.12.2
LDLIBS += /repo/Pass_GPL/asuswrt/release/src-ra-openwrt-4210/router/iptables-1.4.x/libiptc/.libs/libip4tc.o
