# generated by ./configure on Thu Sep 17 14:08:30 CST 2026
SRCDIR = .
CPPFLAGS += -I.
CPPFLAGS += -I/repo/Fail_GPL/asuswrt/release/src-ra-openwrt-4210/router/iptables-1.4.x/include/
LDFLAGS += -L/repo/Fail_GPL/asuswrt/release/src-ra-openwrt-4210/router/iptables-1.4.x/libiptc/
# detected libiptc version 1.4.12.2
LDLIBS += /repo/Fail_GPL/asuswrt/release/src-ra-openwrt-4210/router/iptables-1.4.x/libiptc/.libs/libip4tc.o
