#include "fapi_sys_common.h"
/* Initialize callback hanlders for xRX350 platform */
static SysFapiCB_t fapicb={
	.flag=4,
	.wanSWO = XRX350_wanSWO,
	.moduleLoad = xRX350_module_load,
	.moduleUnLoad = xRX350_module_unload,
    .ProcessorInit = Processor_init,
    .ProcessorUnInit = Processor_uninit,
	.ProcessorStat = stats_counter,
	.SysInit = xRX350_module_init,
	.SysUnInit = xRX350_module_uninit,
	.ppa_init = PPAInit,
	.ppa_uninit = PPAUnInit,
	.sysSet = SysSet,
	.sysGet = SysGet,
	.ppaAdd = PPAIntfAdd,
	.ppaDel = PPAIntfDel,
	.ppaHook = PPAEnHook,
	.SetLinkState = SetLinkState,
	.GetLinkState = GetLinkState,
	.VLANCfgSet = xRX350_VLANCfgSet,
	.RMONGet = RMONGet,
	.getPortId = xRX350_PortIdGet,
	.setPortStatus = SetPortStatus,
	.getPortStatus = xRX350_GetPortStatus,
	.setMaxRate = SetMaxBitRate,
	.getMaxRate = GetMaxBitRate,
	.setDuplexMode = SetDuplexMode,
	.getDuplexMode = GetDuplexMode,
	.EnMirror = xRX350_EnableMirroring,
	.disMirror = xRX350_DisableMirroring, 
	.cfg_SwitchIOCTL = xRX350_cfg_SwitchIOCTL,
};

