# Config file for plc, automatically created by script
[PLC]
network_passwd=HomePlugAV
bridge_ifname=br-lan
plc_ifname=br-lan
aggr_link_rate=0
fwpib_download=1
mac_addr_delta=2
run_mode=HyFi
max_rem_dev=6
topo_disc_timeout=60
pib_path=/lib/firmware/plc/7500/QCA7500-REH172_EN50561-1.pib
debug_level=0
rem_dev_sec_enabled=0
crashscope_enabled=0
qos_tos_enabled=1
qos_tos_priority_0=Low
qos_tos_priority_1=Low
qos_tos_priority_2=Normal
qos_tos_priority_3=Normal
qos_tos_priority_4=High
qos_tos_priority_5=High
qos_tos_priority_6=Highest
qos_tos_priority_7=Highest
qos_vlan_enabled=0
qos_vlan_priority_0=Low
qos_vlan_priority_1=Low
qos_vlan_priority_2=Normal
qos_vlan_priority_3=Normal
qos_vlan_priority_4=High
qos_vlan_priority_5=High
qos_vlan_priority_6=Highest
qos_vlan_priority_7=Highest
qos_threshold_enabled=0
