.TH tonvm 1 "Mar 2014" "plc-utils-2.1.6" "Qualcomm Atheros Powerline Toolkit"

.SH NAME
tonvm - Prepend Lightning/Thunderbolt NVM Image header

.SH SYNOPSIS
.BR tonvm
.RI [ options ]
.IR file
.RI [ file ]
.RI [ ... ]

.SH DESCRIPTION
This tool is used to prepend a NVM header to an image file that can be used by \fBThunderbolt\fR and \fRLightning\fR\ ICs.
The tool makes no attempt to check any internal information other than firmware header checksums, image lengths and image checksums.


.PP
This program handles \fBThunderbolt\fR and \fBLightning\fR chipsets only.

.PP
This program is part of the Qualcomm Atheros Powerline Toolkit.


.SH OPTIONS

.TP
.RB - E
Entry Point address for image. This is the address in SDRAM where execution will start. This value is used by the bootloader during start-up.

.TP
.RB - F
Address in flash where the image should be stored. This is the address in flash (NVM) that the image will be stored at. This value is read and used by the runtime firmware when writing the flash memory.


.TP
.RB - M
Module ID of the image. This value specifies the type of module that this header will be used for. ( 0=softloader,1=firmware,2=pib,3=custom module)


.TP
.RB - m
Sub-Module ID of the image. This value specifies the type of sub-module that this header will be used for. ( used only for custom modules)

.TP
.RB - S
Address in SDRAM where the image should be stored.

.TP
.RB - T
Image type

.TP
.RB - I
Ignore mask

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.BR - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH ARGUMENTS

.TP
.IR file
The name of the image file that should be used to prepend the header.
By convention, Atheros Image files have a \fB.nvm\fR file extension but this program does not enforce this convention.

.SH DISCLAIMER
Qualcomm Atheros firmware file structure and content is proprietary to Qualcomm Atheros, Ocala FL USA.
Consequently, public information is not available.
Qualcomm Atheros reserves the right to change firmware file structure or content or change the name or behavior of any program that inspects or changes firmware files, in future software releases without any obligation to notify or compensate users of such programs.

.SH EXAMPLES
This example reads file abc.nvm and uses it to prepend a header. The entry address is set to 0x00000AFC and the flash address is set to 0x78


.PP
    # tonvm -E 0x00000AFC -F 0x00000078 abc.nvm



.SH SEE ALSO
.BR chknvm ( 1 ),
.BR chkpib ( 1 ),
.BR chkpib1 ( 1 ),
.BR chkpib2 ( 1 ),
.BR int6ktest (7),
.BR nvmmerge ( 1 ),
.BR nvmsplit ( 1 ),
.BR plctest ( 7)

.SH CREDITS 
 Charles Maier <cmaier@qca.qualcomm.com>

