/*
 * Automatically generated C config: don't edit
 */
#undef RTCONFIG_FW_JUMP
#undef RTCONFIG_REALTEK
#undef RTCONFIG_RTL819X
#undef RTCONFIG_RTL8197F
#undef RTCONFIG_RTK_NAND
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#define RTCONFIG_MUSL_LIBC 1
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#define RTCONFIG_ACCEL_PPTPD 1
#undef RTCONFIG_SNMPD
#define RTCONFIG_HTTPS 1
#undef RTCONFIG_BCMARM
#undef RTCONFIG_BCM7
#undef RTCONFIG_BCM_794
#undef RTCONFIG_BCM_7114
#undef RTCONFIG_HND_ROUTER
#undef RTCONFIG_HND_ROUTER_AX
#undef RTCONFIG_HND_ROUTER_AX_675X
#undef RTCONFIG_HND_ROUTER_AX_6756
#undef RTCONFIG_HND_ROUTER_AX_6710
#undef RTCONFIG_SDK504L02_188_1303
#undef RTCONFIG_BCM_502L07P2
#undef RTCONFIG_BCM9
#undef RTCONFIG_BUILDBCM7
#undef RTCONFIG_ROMCFE
#undef RTCONFIG_ROMATECCODEFIX
#undef RTCONFIG_NV128
#define RTCONFIG_NVRAM_SIZE 0x8000
#undef RTCONFIG_DHDAP
#undef RTCONFIG_WLEXE
#undef RTCONFIG_DPSTA
#undef RTCONFIG_DPSR
#undef RTCONFIG_GMAC3
#undef RTCONFIG_BCMSMP
#undef RTCONFIG_BCMFA
#undef RTCONFIG_RGMII_BCM_FA
#undef RTCONFIG_5301X
#undef RTCONFIG_4352_5G
#define RTCONFIG_SSH 1
#undef RTCONFIG_CIFS
#undef RTCONFIG_BRCM_NAND_JFFS2
#define RTCONFIG_JFFS2 1
#undef RTCONFIG_DISKTEST
#undef RTCONFIG_JFFSV1
#undef RTCONFIG_ZEBRA
#define RTCONFIG_QUAGGA 1
#define RTCONFIG_DDNS 1
#define RTCONFIG_INADYN 1
#undef RTCONFIG_L7
#define RTCONFIG_LZO 1
#define RTCONFIG_OPENVPN 1
#define RTCONFIG_IPSEC 1
#undef RTCONFIG_QUICKSEC
#define RTCONFIG_STRONGSWAN 1
#define RTCONFIG_IPSEC_SERVER 1
#undef RTCONFIG_IPSEC_CLIENT
#define RTCONFIG_IPV6 1
#undef RTCONFIG_IMPROXY
#define RTCONFIG_EBTABLES 1
#define RTCONFIG_EMF 1
#undef RTCONFIG_BCMBSD
#undef RTCONFIG_BCMBSD_V2
#undef RTCONFIG_BCMSSD
#undef RTCONFIG_BCMDCS
#undef RTCONFIG_TOAD
#undef RTCONFIG_BCM_MEVENT
#undef RTCONFIG_BCMEVENTD
#undef RTCONFIG_BCM_APPEVENTD
#undef RTCONFIG_HSPOT
#undef RTCONFIG_FANCTRL
#undef RTCONFIG_BCMWL6
#undef RTCONFIG_WIRELESSWAN
#define RTCONFIG_WIRELESSREPEATER 1
#undef RTCONFIG_REPEATER
#undef RTCONFIG_DISABLE_REPEATER_UI
#define RTCONFIG_PROXYSTA 1
#undef RTCONFIG_DISABLE_PROXYSTA_UI
#undef RTCONFIG_CONCURRENTREPEATER
#undef RTCONFIG_VHT80_80
#undef RTCONFIG_VHT160
#undef RTCONFIG_IXIAEP
#undef RTCONFIG_IPERF
#undef RTCONFIG_TCPDUMP
#undef RTCONFIG_DUMP4000
#undef RTCONFIG_TRACEROUTE
#undef RTCONFIG_NETOOL
#define RTCONFIG_PARENTALCTRL 1
#define RTCONFIG_INTERNETCTRL 1
#define RTCONFIG_DNSPRIVACY 1
#undef RTCONFIG_DSL
#undef RTCONFIG_DSL_ANNEX_B
#undef RTCONFIG_DSL_TCLINUX
#undef RTCONFIG_VDSL
#undef RTCONFIG_DSL_BCM
#undef RTCONFIG_DSL_HOST
#undef RTCONFIG_DSL_REMOTE
#undef RTCONFIG_SFPP
#undef RTCONFIG_SYSSTATE
#define RTCONFIG_AHS 1
#define RTCONFIG_LIBASC 1
#define RTCONFIG_DUALWAN 1
#undef RTCONFIG_HW_DUALWAN
#undef RTCONFIG_MFGFW
#undef RTCONFIG_USER_LOW_RSSI
#undef RTCONFIG_WATCH_WLREINIT
#define RTCONFIG_NEW_USER_LOW_RSSI 1
#define RTCONFIG_FRS_FEEDBACK 1
#undef RTCONFIG_PUSH_EMAIL
#undef RTCONFIG_RSYSLOGD
#define RTCONFIG_DBLOG 1
#undef RTCONFIG_NO_USBPORT
#define RTCONFIG_USB 1
#define RTCONFIG_USB_WAN_BACKUP 1
#undef RTCONFIG_USBRESET
#undef RTCONFIG_WIFIPWR
#undef RTCONFIG_XHCIMODE
#define RTCONFIG_MEDIA_SERVER 1
#define RTCONFIG_MEDIASERVER_LIMIT 1
#undef RTCONFIG_NO_DAAPD
#undef RTCONFIG_CLOUDSYNC
#define RTCONFIG_FTP 1
#undef RTCONFIG_FTP_SSL
#undef RTCONFIG_WEBDAV
#define RTCONFIG_SAMBASRV 1
#undef RTCONFIG_SAMBA3
#define RTCONFIG_AWSIOT 1
#undef RTCONFIG_SAMBA36X
#define RTCONFIG_SAMBA4 1
#define RTCONFIG_USB_EXTRAS 1
#define RTCONFIG_E2FSPROGS 1
#define RTCONFIG_EXT4FS 1
#undef RTCONFIG_TFAT
#define RTCONFIG_NTFS 1
#undef RTCONFIG_PARAGON_NTFS
#undef RTCONFIG_TUXERA_NTFS
#define RTCONFIG_OPEN_NTFS3G 1
#undef RTCONFIG_OPENPLUSPARAGON_NTFS
#undef RTCONFIG_OPENPLUSTUXERA_NTFS
#define RTCONFIG_OPEN_NTFS3G_2016 1
#undef RTCONFIG_HFS
#undef RTCONFIG_APFS
#undef RTCONFIG_DISK_MONITOR
#define RTCONFIG_USB_PRINTER 1
#undef RTCONFIG_USB_CDROM
#define RTCONFIG_USB_MODEM 1
#undef RTCONFIG_USB_LESSMODEM
#define RTCONFIG_USB_MODEM_PIN 1
#undef RTCONFIG_USB_SMS_MODEM
#undef RTCONFIG_INTERNAL_GOBI
#undef RTCONFIG_QFIREHOSE
#undef RTCONFIG_DYN_MODEM
#undef RTCONFIG_BRCM_USBAP
#define RTCONFIG_APP_PREINSTALLED 1
#undef RTCONFIG_APP_NETINSTALLED
#undef RTCONFIG_APP_FILEFLEX
#define RTCONFIG_RALINK 1
#undef RTCONFIG_RALINK_RT3883
#undef RTCONFIG_RALINK_RT3052
#undef RTCONFIG_RALINK_MT7620
#define RTCONFIG_RALINK_MT7621 1
#undef RTCONFIG_RALINK_MT7622
#undef RTCONFIG_RALINK_MT7628
#undef RTCONFIG_RALINK_MT7629
#undef RTCONFIG_SPI_FAST_CLOCK
#undef RTCONFIG_EDCCA
#undef RTCONFIG_N56U_SR2
#undef RTCONFIG_AP_CARRIER_DETECTION
#undef RTCONFIG_NEWSSID_REV2
#define RTCONFIG_NEWSSID_REV4 1
#undef RTCONFIG_NEWSSID_REV5
#undef RTCONFIG_RP_NEWSSID_REV3
#undef RTCONFIG_QCA
#undef RTCONFIG_QCA_BIGRATE_WIFI
#undef RTCONFIG_NEW_APP_ARM
#undef RTCONFIG_QCA_ARM
#undef RTCONFIG_QCA953X
#undef RTCONFIG_QCA956X
#undef RTCONFIG_QCN550X
#undef RTCONFIG_SOC_IPQ40XX
#undef RTCONFIG_SOC_IPQ60XX
#undef RTCONFIG_SOC_IPQ50XX
#undef RTCONFIG_FITFDT
#undef RTCONFIG_QCA_VAP_LOCALMAC
#undef RTCONFIG_QCA_PLC_UTILS
#undef RTCONFIG_AR7420
#undef RTCONFIG_QCA7500
#define RTCONFIG_AIR_TIME_FAIRNESS 1
#undef RTCONFIG_POWER_SAVE
#undef RTCONFIG_PAGECACHE_RATIO
#undef RTCONFIG_QCA8033
#undef RTCONFIG_ART2_BUILDIN
#undef RTCONFIG_DEFAULT_AP_MODE
#undef RTCONFIG_DEFAULT_REPEATER_MODE
#define RTCONFIG_ODMPID 1
#undef RTCONFIG_32BYTES_ODMPID
#undef RTCONFIG_TIMEMACHINE
#define RTCONFIG_MDNS 1
#define RTCONFIG_FINDASUS 1
#undef RTCONFIG_REDIRECT_DNAME
#undef RTCONFIG_MTK_TW_AUTO_BAND4
#undef RTCONFIG_QCA_TW_AUTO_BAND4
#define RTCONFIG_LED_ALL 1
#undef RTCONFIG_COMA
#undef CONFIG_LIBBCM
#undef CONFIG_LIBUPNP
#define RTCONFIG_MFP 1
#define RTCONFIG_WPS 1
#undef RTCONFIG_NFC
#undef RTCONFIG_WPS_ENROLLEE
#define RTCONFIG_SHP 1
#undef RTCONFIG_SFP
#undef RTCONFIG_STRACE
#undef RTCONFIG_4M_SFP
#undef RTCONFIG_8M_SFP
#undef RTCONFIG_16M_RAM_SFP
#undef RTCONFIG_GROCTRL
#define RTCONFIG_LANWAN_LED 1
#undef RTCONFIG_WLAN_LED
#undef RTCONFIG_FAKE_ETLAN_LED
#undef RTCONFIG_EXT_LED_WPS
#undef RTCONFIG_SWMODE_SWITCH
#undef RTCONFIG_WL_AUTO_CHANNEL
#undef RTCONFIG_SMALL_FW_UPDATE
#undef RTCONFIG_WIRELESS_SWITCH
#undef RTCONFIG_WIFI_TOG_BTN
#undef RTCONFIG_WPS_RST_BTN
#define RTCONFIG_WPS_ALLLED_BTN 1
#define RTCONFIG_SW_CTRL_ALLLED 1
#undef RTCONFIG_TURBO_BTN
#undef RTCONFIG_LOGO_LED
#undef RTCONFIG_LED_BTN
#undef RTCONFIG_USBEJECT
#define RTCONFIG_AUTODICT 1
#undef RTCONFIG_AUTOLIVEUPDATE_ZIP
#undef RTCONFIG_ISP_METER
#undef RTCONFIG_NVRAM_64K
#undef RTCONFIG_USB_XHCI
#undef RTCONFIG_WLMODULE_RT3090_AP
#undef RTCONFIG_WLMODULE_RT3352_INIC_MII
#undef RTCONFIG_WLMODULE_MT7610_AP
#undef RTCONFIG_WLMODULE_RLT_WIFI
#undef RTCONFIG_WLMODULE_MT7603E_AP
#undef RTCONFIG_WLMODULE_MT7628_AP
#undef RTCONFIG_WLMODULE_MT7615E_AP
#undef RTCONFIG_WLMODULE_MT7663E_AP
#undef RTCONFIG_WLMODULE_MT7629_AP
#undef RTCONFIG_WLMODULE_MT7622_AP
#define RTCONFIG_WLMODULE_MT7915D_AP 1
#define RTCONFIG_PSISTLOG 1
#define RTCONFIG_DUAL_TRX 1
#undef RTCONFIG_DUAL_TRX2
#undef RTCONFIG_TEST_FLIPBITS
#undef RTCONFIG_UBI
#undef RTCONFIG_UBIFS
#undef RTCONFIG_YAFFS
#undef RTCONFIG_SAVEJFFS
#undef RTCONFIG_OPTIMIZE_XBOX
#define RTCONFIG_NEW_REGULATION_DOMAIN 1
#undef RTCONFIG_DYN_DICT_NAME
#undef RTCONFIG_LAN4WAN_LED
#undef RTCONFIG_DMALLOC
#undef RTCONFIG_JFFS2ND_BACKUP
#define RTCONFIG_TEMPROOTFS 1
#undef RTCONFIG_ATEUSB3_FORCE
#undef RTCONFIG_JFFS2LOG
#undef RTCONFIG_WPSMULTIBAND
#define RTCONFIG_RALINK_DFS 1
#undef RTCONFIG_ENGINEERING_MODE
#define RTCONFIG_VPNC 1
#undef RTCONFIG_KYIVSTAR
#undef RTCONFIG_NO_WANPORT
#undef RTCONFIG_WANPORT2
#undef RTCONFIG_MULTIWAN_CFG
#undef RTCONFIG_TFTP_SERVER
#undef RTCONFIG_ETRON_XHCI
#undef RTCONFIG_ETRON_XHCI_USB3_LED
#undef RTCONFIG_WPS_LED
#undef RTCONFIG_MMC_LED
#undef RTCONFIG_RESET_SWITCH
#undef RTCONFIG_WANRED_LED
#undef RTCONFIG_WANLEDX2
#undef RTCONFIG_R10G_LED
#undef RTCONFIG_PWRRED_LED
#undef RTCONFIG_FAILOVER_LED
#undef RTCONFIG_SATA_LED
#undef RTCONFIG_BLINK_LED
#undef RTCONFIG_LEDS_CLASS
#undef RTCONFIG_EJUSB_BTN
#undef RTCONFIG_M2_SSD
#undef RTCONFIG_WIGIG
#undef RTCONFIG_CFE_NVRAM_CHK
#undef RTCONFIG_DEBUG
#undef RTCONFIG_VALGRIND
#define RTCONFIG_HAS_5G 1
#undef RTCONFIG_HAS_5G_2
#undef RTCONFIG_TFTP
#undef RTCONFIG_QTN
#undef RTCONFIG_ALPINE
#undef RTCONFIG_QSR10G
#undef RTCONFIG_LANTIQ
#undef RTCONFIG_N18UTXBF
#define RTCONFIG_BWDPI 1
#undef RTCONFIG_TRAFFIC_LIMITER
#undef RTCONFIG_SPEEDTEST
#undef RTCONFIG_BONDING
#undef RTCONFIG_BONDING_WAN
#undef RTCONFIG_UIDEBUG
#undef RTCONFIG_ROG
#undef RTCONFIG_ROG_UI
#undef RTCONFIG_GEOIP
#undef RTCONFIG_GEOIP_EG
#undef RTCONFIG_TRANSMISSION
#define RTCONFIG_TCODE 1
#undef RTCONFIG_WIFILOGO
#undef RTCONFIG_JFFS2USERICON
#undef RTCONFIG_EXT_RTL8365MB
#undef RTCONFIG_EXT_RTL8370MB
#undef RTCONFIG_EXT_BCM53134
#undef RTCONFIG_RTL8221VB
#undef RTCONFIG_EXTPHY_BCM84880
#undef RTCONFIG_BCM_HND_CRASHLOG
#undef RTCONFIG_TOR
#define RTCONFIG_TR069 1
#undef RTCONFIG_TR181
#undef RTCONFIG_ISP_OPTUS
#undef RTCONFIG_ACS_SUBNET
#undef RTCONFIG_SERIALSIZE_15
#undef RTCONFIG_ISP_XLNPROVU
#undef RTCONFIG_STAINFO
#undef RTCONFIG_CLOUDCHECK
#undef RTCONFIG_GETREALIP
#undef CONFIG_ASUS_APCLI_WPS
#define RTCONFIG_TUNNEL 1
#undef RTCONFIG_UPLOADER
#undef RTCONFIG_AICLOUD_TUNNEL
#define RTCONFIG_AIHOME_TUNNEL 1
#undef RTCONFIG_CFEZ
#undef RTCONFIG_RESTRICT_GUI
#undef RTCONFIG_LACP
#undef RTCONFIG_KEY_GUARD
#undef RTCONFIG_RECVFILE
#undef RTCONFIG_WTFAST
#define RTCONFIG_ALEXA 1
#undef RTCONFIG_IFTTT
#define RTCONFIG_UTF8_SSID 1
#undef RTCONFIG_ERP_TEST
#define RTCONFIG_REBOOT_SCHEDULE 1
#undef RTCONFIG_CAPTIVE_PORTAL
#undef RTCONFIG_CP_FREEWIFI
#undef RTCONFIG_CP_ADVANCED
#undef RTCONFIG_UPNPC
#undef RTCONFIG_UPNPC_NEW
#undef RTCONFIG_AUPNPC
#define RTCONFIG_MULTICAST_IPTV 1
#undef RTCONFIG_BONJOUR
#define RTCONFIG_FORCE_AUTO_UPGRADE 1
#undef RTCONFIG_CHILLISPOT
#undef RTCONFIG_COOVACHILLI
#undef RTCONFIG_FREERADIUS
#undef RTCONFIG_TUXERA_SMBD
#undef RTCONFIG_BCMASPMD
#undef RTCONFIG_FBT
#undef RTCONFIG_WLCLMLOAD
#define RTCONFIG_MUMIMO 1
#define RTCONFIG_NOTIFICATION_CENTER 1
#define RTCONFIG_PROTECTION_SERVER 1
#define RTCONFIG_WLCEVENTD 1
#undef RTCONFIG_HAPDEVENT
#define RTCONFIG_6RELAYD 1
#define RTCONFIG_SOFTWIRE46 1
#define RTCONFIG_OCNVC 1
#undef RTCONFIG_DSLITE
#undef RTCONFIG_PORT_BASED_VLAN
#undef RTCONFIG_TAGGED_BASED_VLAN
#undef RTCONFIG_DISABLE_NETWORKMAP
#undef RTCONFIG_WAN_AT_P4
#undef RTCONFIG_MTK_REP
#undef RTCONFIG_ATED122
#undef RTCONFIG_NOIPTV
#define RTCONFIG_MTK_NAND 1
#define RTCONFIG_RALINK_EDCCA 1
#define RTCONFIG_AUTOCOVER_SIP 1
#define RTCONFIG_DEFLAN50 1
#undef RTCONFIG_ALL_DEF_LAN50
#undef RTCONFIG_VPN_FUSION
#undef RTCONFIG_LBR_AGGR
#undef RTCONFIG_FLATLAS
#undef RTCONFIG_WBD
#define RTCONFIG_QAM256_2G 1
#define RTCONFIG_QAM1024_5G 1
#define RTCONFIG_MUMIMO_2G 1
#define RTCONFIG_MUMIMO_5G 1
#undef RTCONFIG_CONNTRACK
#undef RTCONFIG_PERMISSION_MANAGEMENT
#undef RTCONFIG_DNSSEC
#undef RTCONFIG_DNSSEC_OPENSSL
#undef RTCONFIG_DNSSEC_NETTLE
#define RTCONFIG_DNSFILTER 1
#define RTCONFIG_LETSENCRYPT 1
#undef RTCONFIG_DETWAN
#define RTCONFIG_CFGSYNC 1
#undef RTCONFIG_CFGSYNC_LOCSYNC
#undef RTCONFIG_LP5523
#undef RTCONFIG_FIXED_BRIGHTNESS_RGBLED
#undef RTCONFIG_SINGLE_SSID
#undef RTCONFIG_SSID_AMAPS
#undef RTCONFIG_PTHSAFE_POPEN
#undef RTCONFIG_HIDDEN_BACKHAUL
#undef RTCONFIG_ETHBACKHAUL
#undef RTCONFIG_AUTHSUPP
#undef RTCONFIG_FBWIFI
#define RTCONFIG_ADV_RAST 1
#define RTCONFIG_BCN_RPT 1
#undef RTCONFIG_NBR_RPT
#undef RTCONFIG_ADTBW_AFTER_RADARDETECTED
#define RTCONFIG_BTM_11V 1
#undef RTCONFIG_FAST_ACL_SET
#define RTCONFIG_FORCE_ROAMING 1
#define RTCONFIG_STA_AP_BAND_BIND 1
#define RTCONFIG_11K_RCPI_CHECK 1
#undef RTCONFIG_RAST_NONMESH_KVONLY
#define RTCONFIG_CONN_EVENT_TO_EX_AP 1
#undef RTCONFIG_WLCSCAN_RSSI
#undef RTCONFIG_BT_CONN
#undef RTCONFIG_BT_CONN_USB
#undef RTCONFIG_BT_CONN_UART
#undef RTCONFIG_CSR8811
#undef RTCONFIG_RGBLED
#undef RTCONFIG_BCM_CLED
#undef RTCONFIG_SINGLE_LED
#undef RTCONFIG_PIPEFW
#undef RTCONFIG_URLFW
#undef RTCONFIG_AURASYNC
#undef RTCONFIG_I2CTOOLS
#undef RTCONFIG_MTK_8021X3000
#define RTCONFIG_MTK_8021XD3000 1
#undef RTCONFIG_INTEL
#undef RTCONFIG_DBG_BLUECAVE_OBD
#define RTCONFIG_AMAS 1
#define RTCONFIG_AMAS_WGN 1
#undef RTCONFIG_AMASDB
#undef RTCONFIG_BATMAN_ADV
#define RTCONFIG_AVBLCHAN 1
#undef RTCONFIG_LYRA_5G_SWAP
#define RTCONFIG_NO_SELECT_CHANNEL 1
#define RTCONFIG_USB_SWAP 1
#undef RTCONFIG_SW_DEVLED
#undef RTCONFIG_LYRA_HIDE
#undef RTCONFIG_PORT2_DEVICE
#define RTCONFIG_NVRAM_ENCRYPT 1
#undef RTCONFIG_WIFI_PROXY
#define RTCONFIG_HD_SPINDOWN 1
#define RTCONFIG_MASTER_DET 1
#undef RTCONFIG_ADTBW
#undef RTCONFIG_TXBF_BAND3ONLY
#define RTCONFIG_SW_HW_AUTH 1
#define RTCONFIG_LIBASUSLOG 1
#undef RTCONFIG_BCM_CEVENTD
#define RTCONFIG_ETHOBD 1
#define RTCONFIG_DWB 1
#undef RTCONFIG_NO_TRY_DWB_PROFILE
#undef RTCONFIG_FRONTHAUL_DWB
#undef RTCONFIG_AMAS_ETHDETECT
#define RTCONFIG_BHCOST_OPT 1
#undef RTCONFIG_CONNDIAG
#undef RTCONFIG_REPEATER_STAALLBAND
#undef RTCONFIG_WTF_REDEEM
#undef RTCONFIG_QCA_LBD
#undef RTCONFIG_AMAS_WDS
#undef RTCONFIG_AMAS_MTK_EZWDS
#define RTCONFIG_MTK_BSD 1
#undef RTCONFIG_COBRAND
#undef RTCONFIG_GEFORCENOW
#undef RTCONFIG_FPROBE
#define RTCONFIG_ISP_CUSTOMIZE 1
#undef RTCONFIG_IPERF3
#define RTCONFIG_ASUSCTRL 1
#define RTCONFIG_PRELINK 1
#define RTCONFIG_MSSID_PRELINK 1
#undef RTCONFIG_OPENSSL10
#define RTCONFIG_OPENSSL11 1
#undef RTCONFIG_NO_PTHREAD_TIMEDWAIT
#undef RTCONFIG_OPEN_NAT
#undef RTCONFIG_BRCM_HOSTAPD
#define RTCONFIG_FRS_LIVE_UPDATE 1
#define RTCONFIG_AUTO_FW_UPGRADE 1
#undef RTCONFIG_BETA_UPGRADE
#undef RTCONFIG_REVERTFW
#define RTCONFIG_ASD 1
#define RTCONFIG_LIVE_UPDATE_RSA 1
#undef RTCONFIG_UUPLUGIN
#undef RTCONFIG_TCPLUGIN
#undef RTCONFIG_ATEFROMWAN
#undef RTCONFIG_WIFI_DRV_DISABLE
#undef RTCONFIG_BROOP
#undef RTCONFIG_BROOP_LED
#undef RTCONFIG_GN_WBL
#undef RTCONFIG_AMAZON_WSS
#undef RTCONFIG_OOKLA
#undef RTCONFIG_OOKLA_LITE
#undef RTCONFIG_QCA_MCSD
#undef RTCONFIG_QSDK6PLUS
#undef RTCONFIG_QSDK10CS
#undef RTCONFIG_AMAS_ADTBW
#undef RTCONFIG_AMAS_UNIQUE_MAC
#define RTCONFIG_ACCOUNT_BINDING 1
#define RTCONFIG_AMAS_SYNC_2G_BW 1
#undef RTCONFIG_NoETH
#undef RTCONFIG_TAIL_INFO
#undef RTCONFIG_WL_SCHED_V2
#define RTCONFIG_PC_SCHED_V2 1
#define RTCONFIG_SCHED_V2 1
#undef RTCONFIG_WL_SCHED_V3
#define RTCONFIG_PC_SCHED_V3 1
#undef RTCONFIG_SCHED_V3
#undef RTCONFIG_MULTIFW
#define RTCONFIG_RE_RECONNECT 1
#undef RTCONFIG_BH_SWITCH_ETH_FIRST
#define RTCONFIG_CAPTCHA 1
#undef RTCONFIG_MULTISERVICE_WAN
#define RTCONFIG_VIF_ONBOARDING 1
#undef RTCONFIG_WIFI6E
#define RTCONFIG_SYSCLASSGPIO 1
#define RTCONFIG_SAVE_WL_NVRAM_BOTH 1
#undef RTCONFIG_SWCONFIG
#define RTCONFIG_MTK_NAND_BLOCK2 1
#undef RTCONFIG_QCA_PLC2
#undef RTCONFIG_VAR_NVRAM
#undef RTCONFIG_BCM_OAM
#undef RTCONFIG_NEW_PHYMAP
#define RTCONFIG_INSTANT_GUARD 1
#undef RTCONFIG_GAME_MODE
#define RTCONFIG_BHSWITCH_RE_SELFOPT 1
#define RTCONFIG_PREFERAP_RE_SELFOPT 1
#define RTCONFIG_MAX_RE 9
#undef RTCONFIG_FRONTHAUL_DBG
#define RTCONFIG_RALINK_BUILDIN_WIFI 1
#undef RTCONFIG_DLOADER
#undef RTCONFIG_FIBOCOM_FG621
#undef RTCONFIG_WIREGUARD
#undef RTCONFIG_OWE_TRANS
#undef RTCONFIG_TPVPN
#undef RTCONFIG_SPECIFIC_PPPOE
#undef RTCONFIG_ACL96
#define RTCONFIG_ISP_CUSTOMIZE_TOOL 1
#undef RTCONFIG_ISPCTRL
#define RTCONFIG_GOOGLE_ASST 1
#undef RTCONFIG_EXTEND_LIMIT
#undef RTCONFIG_COMFW
#undef RTCONFIG_QUADBAND
#define RTCONFIG_LLDPD_0_9_8 1
#undef RTCONFIG_LLDPD_1_0_11
#undef RTCONFIG_FSMD
#define RTCONFIG_3LANPORT_DEVICE 1
#undef RTCONFIG_HW_DOG
#undef RTCONFIG_AMAS_CENTRAL_CONTROL
#undef RTCONFIG_BANDINDEX_NEW
#undef RTCONFIG_MT798X
#undef RTCONFIG_DUPVIF
#undef RTCONFIG_AVOID_TZ_ENV
#define RTCONFIG_ECC256 1
#undef RTCONFIG_PASS_V2
#define RTCONFIG_SECURE_BY_DEFAULT 1
