/*
 * NVRAM variable manipulation (Linux user mode half)
 *
 * Copyright 2005, Broadcom Corporation
 * All Rights Reserved.
 *
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: nvram_linux.c,v 1.18 2005/05/16 12:35:03 honor Exp $
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <error.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>

#include <fapi_wlan_private.h>
#include <fapi_wlan.h>
#include <help_objlist.h>
#include <wlan_config_api.h>

enum
{
	BADAPI = (-1),
	ERROR_VALUE = (-1),
	FLAG = 0,
	LOAD,
	INIT,
	UNINIT,
	RESET,
	CREATE_CONFIG,
	FACTORY_DEAFULTS,
	CREATE_VAP,
	DELETE_VAP,
	SET_RADIO_TR181,
	SET_SSID_TR181,
	SET_AP_TR181,
	SET_SECURITY_TR181,
	SET_WPS,
	SET_WMM_STA,
	SET_WMM_AP,
	SET_WDS,
	SET_HOTSPOT,
	GET_INTERFACE_NAME,
	GET_CHANNEL,
	SET_CHANNEL,
	GET_AUTO_CHANNEL_ENABLE,
	SET_AUTO_CHANNEL_ENABLE,
	GET_RADIO_ENABLE,
	SET_RADIO_ENABLE,
	GET_ENABLE,
	SET_ENABLE,
	GET_SSID,
	SET_SSID,
	GET_SSID_ADVERTISEMENT_ENABLED, 
	SET_SSID_ADVERTISEMENT_ENABLED,
	GET_MAC_ADD_CONTROL_ENABLED,
	SET_MAC_ADD_CONTROL_ENABLED,
	GET_BEACON_TYPE,
	SET_BEACON_TYPE,
	GET_KEY_PASS_PHRASE,
	SET_KEY_PASS_PHRASE,
	GET_WEP_KEY_PASSPHRASE,
	SET_WEP_KEY_PASSPHRASE,
	GET_BASIC_ENC_MODE,
	SET_BASIC_ENC_MODE,
	GET_BASIC_AUTH_MODE,
	SET_BASIC_AUTH_MODE,
	GET_WPA_ENC_MODE,
	SET_WPA_ENC_MODE, 
	GET_WPA_AUTH_MODE,
	SET_WPA_AUTH_MODE,
	GET_SUPPORTED_FREQUENCY_BANDS,
	GET_PRE_SHARED_KEY,
	SET_PRE_SHARED_KEY,
	GET_AP_SECURITY_MODE_ENABLED,
	IF_CONFIG_UP,
	IF_CONFIG_DOWN,
	GET_BASE_BSSID,
	GET_STATUS,
	GET_MAX_BIT_RATE,
	GET_STANDARD,
	GET_WMM_ENABLE,
	NOTIFY,
	GET_CHANNEL_MODE,
	SET_CHANNEL_MODE,
	GET_POSSIBLE_CHANNELS,
	ADD_ACL_DEV,
	DEL_ACL_DEV,
	GET_ACL_DEV_NUM,
	GET_MAC_ADD_CONTROL_MODE,
	SET_MAC_ADD_CONTROL_MODE,
	GET_WIFI_ENABLE_STATUS_BOOL,
	GET_WPA_REKEY_INTERVAL,
	SET_WPA_REKEY_INTERVAL,
	GET_INDEX_FROM_NAME,
	GET_ASSOC_DEVICES_NUM,
	SET_AP_BRIDGING,
	GET_RADIO_INDEX,
	GET_RADIO_ACTIVE,
	GET_WPS_ENABLE,
	SET_WPS_ENABLE,
	GET_WPS_DEVICE_PIN,
	SET_WPS_DEVICE_PIN,
	GET_WPS_CONFIG_METHOD_ENABLED,
	SET_WPS_CONFIG_METHOD_ENABLED,
	GET_WPS_CONFIGURATION_STATE,
	SET_WPS_PBC_TRIGGER,
	CANCEL_WPS,
	GET_MAX_STATIONS,
	SET_MAX_STATIONS,
	KICK_ACL_ASSOCIATED_DEVICES,
	GET_AP_WMM_CAPABILITY,
	GET_AP_UAPSD_CAPABILITY,
	GET_AP_ISOLATION_ENABLE,
	GET_AP_WMM_UAPSD_ENABLE,
	SET_AP_WMM_UAPSD_ENABLE,
	GET_AP_ACL_DEVICES,
	GET_AP_SECURITY_RADIUS_SERVER_IP,
	SET_AP_SECURITY_RADIUS_SERVER_IP,
	GET_AP_SECURITY_RADIUS_SERVER_PORT,
	SET_AP_SECURITY_RADIUS_SERVER_PORT,
	GET_AP_SECURITY_RADIUS_SERVER,
	SET_AP_SECURITY_RADIUS_SERVER,
	GET_WEP_KEY,
	SET_WEP_KEY,
	GET_WEP_KEY_INDEX,
	SET_WEP_KEY_INDEX,
	START_MONITORING,
	STATION_STEER_TR181,
	STATION_STEER,
	STATION_ALLOW_TR181,
	STATION_ALLOW,
	CHANNEL_SWITCH_TR181,
	CHANNEL_SWITCH,
	UNASSOCIATED_DEVICES_INFO_REQ_TR181,
	UNASSOCIATED_DEVICES_INFO_REQ,
	RESTRICTED_CHANNEL_SET_TR181,
	RESTRICTED_CHANNEL_SET,
	FAILSAFE_CHANNEL_SET_TR181,
	FAILSAFE_CHANNEL_SET,
	STATION_MEASUREMENT_GET,
	VAP_MEASUREMENT_GET,
	RADIO_INFO_GET,
	ACS_REPORT_GET,
	FAILSAFE_CHANNEL_GET,
	RESTRICTED_CHANNEL_GET,
	WLAN_DOWN,
	FACTORY_RESET_RADIOS,
	GET_TRANSMIT_POWER,
	SET_TRANSMIT_POWER,
	SET_STBC_ENABLE,
	GET_AMSDU_ENABLE,
	SET_AMSDU_ENABLE,
	SET_SHORT_GUARD_INTERVAL,
	GET_TX_CHAIN_MASK,
	SET_TX_CHAIN_MASK,
	GET_RX_CHAIN_MASK,
	SET_RX_CHAIN_MASK,
	GET_RADIO_IEEE_ENABLED,
	GET_RADIO_IEEE_SUPPORTED,
	GET_RADIO_AUTO_CH_REFRESH_PERIOD_SUPPORTED,
	GET_RADIO_AUTO_CH_REFRESH_PERIOD,
	GET_RADIO_DCS_ENABLE,
	SET_RADIO_DCS_ENABLE,
	SET_WMM_UAPSD_ENABLE,
	SET_WMM_OG_AIFSN,
	GET_WMM_OG_AIFSN,
	SET_WMM_OG_ECW_MIN,
	GET_WMM_OG_ECW_MIN,
	SET_WMM_OG_ECW_MAX,
	GET_WMM_OG_ECW_MAX,
	SET_WMM_OG_TX_OP,
	GET_WMM_OG_TX_OP,
	SET_WMM_IC_AIFSN,
	GET_WMM_IC_AIFSN,
	SET_WMM_IC_ECW_MIN,
	GET_WMM_IC_ECW_MIN,
	SET_WMM_IC_ECW_MAX,
	GET_WMM_IC_ECW_MAX,
	SET_WMM_IC_TX_OP,
	GET_WMM_IC_TX_OP,
	SET_BEACON_INTERVAL,
	GET_RADIO_BASIC_DATA_TRANSMIT_RATES,
	SET_RADIO_BASIC_DATA_TRANSMIT_RATES,
	GET_RADIO_BEACON_PERIOD,
	SET_RADIO_BEACON_PERIOD,
	GET_RADIO_GUARD_INTERVAL,
	SET_RADIO_GUARD_INTERVAL,
	GET_RADIO_UP_TIME,
	GET_AP_RETRY_LIMIT,
	SET_AP_RETRY_LIMIT,
	GET_BRIDGE_NAME,
	SET_BRIDGE_NAME
};
int wave_get_channel(int unit)
{
	unsigned int channel = -1;
	int retVal;

	retVal = wlan_getChannel(unit, &channel);
	fprintf(stderr, "wlan_getChannel=[%d]\n", channel);
	return channel;
}

int main(int argc, char **argv)
{
	wave_get_channel(1);
	return 1;
}

char *paramValueFromObjGet(ObjList *objPtr, char *objName, char *paramName)
{
	ObjList   *tmpHwInitObj = NULL;
	ParamList *param = NULL;
	char      *paramValue = NULL;

	FOR_EACH_OBJ(objPtr, tmpHwInitObj)
	{
		if ( ! strcmp(GET_OBJ_NAME(tmpHwInitObj), objName) )
		{
			FOR_EACH_PARAM(tmpHwInitObj, param)
			{
				if (!strcmp(GET_PARAM_NAME(param), paramName))
				{
					paramValue = GET_PARAM_VALUE(param);
					return paramValue;
				}
			}
		}
	}

	return paramValue;
}

int wave_get_radio_channel(int index)
{
	ObjList *dbObjPtr = NULL;

	int retVal = UGW_FAILURE;
	dbObjPtr = HELP_CREATE_OBJ(SOPT_OBJVALUE);
	//Format:  fapi_wlan_cli radioInfoGet -i index
	//Example: fapi_wlan_cli radioInfoGet -i 1
	retVal = fapi_wlan_start_monitoring_native(index, NULL, FLAG);
	if (retVal == 0)
		retVal = fapi_wlan_radio_info_get_native(index, dbObjPtr, FLAG);

	fprintf(stderr, "channel:[%s]\n", 
				paramValueFromObjGet(dbObjPtr, "Device.WiFi.Radio",
					"Channel"));
	return atoi(paramValueFromObjGet(dbObjPtr, "Device.WiFi.Radio",
					"Channel"));
}

int wave_get_channel_list(int index, char *channels)
{
	wlan_getPossibleChannels(index, channels);

	return 1;
}

