#define SSHDIST_APPS
#define SSHDIST_APPS_CRYPTUTILS
#define SSHDIST_APPS_LDAPUTILS
#define SSHDIST_APPS_PERFUTILS
#define SSHDIST_APPUTIL
#define SSHDIST_APPUTIL_KEYUTIL
#define SSHDIST_APPUTIL_SSH1ENCODE
#define SSHDIST_ASN1
#define SSHDIST_CERT
#define SSHDIST_CERT_CRMF
#define SSHDIST_CERT_OCSP
#define SSHDIST_CERT_PKCS10
#define SSHDIST_CRYPT
#define SSHDIST_CRYPTO
#define SSHDIST_CRYPTO_RANDOM
#define SSHDIST_CRYPTO_RANDOM_POLL
#define SSHDIST_CRYPT_NIST_SP_800_90
#define SSHDIST_CRYPT_COMPRESS
#define SSHDIST_CRYPT_DES
#define SSHDIST_CRYPT_DH
#define SSHDIST_CRYPT_DL
#define SSHDIST_CRYPT_DL_GENERATE
#define SSHDIST_CRYPT_DL_IKE_GROUPS
#define SSHDIST_CRYPT_DSA
#define SSHDIST_CRYPT_ECP
#define SSHDIST_CRYPT_BRAINPOOL_ECP
#define SSHDIST_CRYPT_EXPORT
#define SSHDIST_CRYPT_GENPKCS
#define SSHDIST_CRYPT_GENPKCS_DH
#define SSHDIST_CRYPT_GENPKCS_PRIVATE
#define SSHDIST_CRYPT_GENPKCS_PUBLIC
#define SSHDIST_CRYPT_HMAC
#define SSHDIST_CRYPT_MD5
#define SSHDIST_CRYPT_MODE_CCM
#define SSHDIST_CRYPT_MODE_GCM
#define SSHDIST_CRYPT_PROXYKEY
#define SSHDIST_CRYPT_RIJNDAEL
#define SSHDIST_CRYPT_RSA
#define SSHDIST_CRYPT_SELF_TESTS
#define SSHDIST_CRYPT_SHA
#define SSHDIST_CRYPT_SHA256
#define SSHDIST_CRYPT_SHA512
#define SSHDIST_CRYPT_SSHMACS
#define SSHDIST_CRYPT_XCBCMAC
#define SSHDIST_DIRECTORY_HTTP
#define SSHDIST_DIRECTORY_TLS
#define SSHDIST_EAP
#define SSHDIST_EAP_MSCHAPV2
#define SSHDIST_EAP_TLS
#define SSHDIST_EXTERNALKEY
#define SSHDIST_EXTKEY_SOFT_ACCELERATOR_PROV
#define SSHDIST_FUNCTIONALITY_TLS
#define SSHDIST_HTTP_CLIENT
#define SSHDIST_HTTP_SERVER
#define SSHDIST_IKEV1
#define SSHDIST_IKEV2
#define SSHDIST_IKE_CERT_AUTH
#define SSHDIST_IKE_EAP_AUTH
#define SSHDIST_IKE_MOBIKE
#define SSHDIST_IKE_XAUTH
#define SSHDIST_IKE_REDIRECT
#define SSHDIST_IPSEC
#define SSHDIST_IPSEC_COMPRESSION_DEFLATE
#define SSHDIST_IPSEC_COMPRESSION_LZS
#define SSHDIST_IPSEC_DNSPOLICY
#define SSHDIST_IPSEC_HWACCEL
#define SSHDIST_IPSEC_IPCOMP
#define SSHDIST_IPSEC_MOBIKE
#define SSHDIST_IPSEC_NAT_TRAVERSAL
#define SSHDIST_ISAKMP_CFG_MODE
#define SSHDIST_L2TP
#define SSHDIST_LDAP
#define SSHDIST_MATH
#define SSHDIST_MATH_2ADIC
#define SSHDIST_MATH_ARITHMETIC
#define SSHDIST_MATH_ECP
#define SSHDIST_MATH_INTMOD
#define SSHDIST_MATH_MONTGOMERY
#define SSHDIST_MATH_NAF
#define SSHDIST_MATH_POWM
#define SSHDIST_MATH_SIEVE
#define SSHDIST_PLATFORM_LINUX
#define SSHDIST_QUICKSEC
#define SSHDIST_QUICKSECPM
#define SSHDIST_TESTS_INPLACE
#define SSHDIST_UTIL
#define SSHDIST_UTIL_AUDIT
#define SSHDIST_UTIL_DNS_RESOLVER
#define SSHDIST_UTIL_TCP
#define SSHDIST_VALIDATOR
#define SSHDIST_VALIDATOR_HTTP
#define SSHDIST_VALIDATOR_LDAP
#define SSHDIST_VALIDATOR_OCSP
#define SSHDIST_VALIDATOR_PKCS
#define SSHDIST_XML
#define SSHDIST_ZLIB
#define SSHDIST_ZLIB_LEVEL_DETECTION

#if !defined(QUICKSEC_DIST_CLIENT) && \
    !defined(QUICKSEC_DIST_SERVER) && \
    !defined(QUICKSEC_DIST_CLIENT_SERVER)

#define QUICKSEC_DIST_CLIENT_SERVER

#endif

#if defined(QUICKSEC_DIST_CLIENT) || defined(QUICKSEC_DIST_CLIENT_SERVER)

#define SSHDIST_EAP_SIM
#define SSHDIST_EAP_AKA
#define SSHDIST_IPSEC_REMOTE_ACCESS_CLIENT
#define SSHDIST_IPSEC_VIRTUAL_ADAPTERS
#define SSHDIST_IPSEC_XAUTH_CLIENT
#define SSHDIST_SIM
#define SSHDIST_SIM_SAMPLE
#define SSHDIST_ISAKMP_CFG_MODE_RULES

#endif

#if defined(QUICKSEC_DIST_SERVER) || defined(QUICKSEC_DIST_CLIENT_SERVER)

#define SSHDIST_IKE_ID_LIST
#define SSHDIST_IPSEC_DHCP
#define SSHDIST_IPSEC_REMOTE_ACCESS_SERVER
#define SSHDIST_IPSEC_SA_EXPORT
#define SSHDIST_IPSEC_SCTP_MULTIHOME
#define SSHDIST_IPSEC_XAUTH_SERVER
#define SSHDIST_RADIUS

#endif
