.TH adccap3 1 "Mar 2014" "plc-utils-2.1.6" "Qualcomm Atheros Powerline Toolkit"

.SH NAME
adccap3 - Qualcomm Atheros ADC Capture Utility

.SH SYNOPSIS
.BR adccap3
.RI [ options ] 
.RI [ device ]

.SH DESCRIPTION
Collect and display ADC data from a PLC device using the Qualcomm Atheros manufacter-specific VS_DBG_INFO management message.
The VS_DBG_INFO message is a multi purpose message where ADC capture is one of several options available.
The VS_DBG_INFO ADC capture option is recognized by runtime firmware and one custom applet designed to capture ADC data.

.PP
Captured data is saved as an ASCII text file containing 6528 positive integer values, one value per line.

.SH OPTIONS

.TP
-\fBc\fI coupling\fR
The coupling.
Use the number \fB0\fR, or the string "\fBpri\fR", for primary coupling.
Use the number \fB1\fR, or the string "\fBalt\fR", for alternate coupling.
This program will accept any numeric value from \fB0\fR through \fB255\fR but runtime firmware will reject invalid values.
The default value is \fB0\fR.

.TP
-\fBg\fI gain\fR
The RX gain.
Permitted values are \fB0\fR through \fB31\fR.
The previously set gain is used by the powerline device when this option is omitted.

.TP
-\fBi\fR \fIinterface\fR
Select the host Ethernet interface.
All requests are sent via this host interface and only reponses received via this host interface are recognized.
The default interface is \fBeth1\fR because most people use \fBeth0\fR as their principle network connection; however, if environment string "PLC" is defined then it takes precedence over the default interface.
This option then takes precedence over either default.

.TP
.RB - n
Start data capture now.

.TP
.RB - r
Read captured data.
Captured data expires after about 20 seconds.

.TP
.RB - s
Start data capture after synchronization.

.TP
.RB - q
Quiet mode.
Suppresses status messages on stderr.

.TP
-\fBt\fI milliseconds\fR
The channel timeout in milliseconds.
The default is \fB50\fR milliseconds but this can be increased if needed.

.TP
.RB - v
Verbose mode.
Print additional information on stdout.

.TP
-\fBw\fI seconds\fR
The number of seconds to wait between capture and read operations.
A non-zero wait time automatically initiates a capture then wait then read sequence for you.
Valid values are \fB0\fR through \fB30\fR seconds.
The default is \fB0\fR seconds.

.TP
.RB - ? ,-- help
Print program help summary on stdout.
This option takes precedence over other options on the command line.

.TP
.RB - ! ,-- version
Print program version information on stdout.
This option takes precedence over other options on the command line.
Use this option when sending screen dumps to Atheros Technical Support so that they know exactly which version of the Linux Toolkit you are using.

.SH DEVICES
Powerline devices use Ethernet hardware, or Media Access Control (MAC), addresses.
Device addresses are 12 hexadecimal digits (\fB0123456789ABCDEFabcdef\fR) in upper, lower or mixed case.
Individual octets may be separated by colons, for clarity, but not all octets need to be seperated.
For example, "00b052000001", "00:b0:52:00:00:01" and "00b052:000001" are valid and equivalent.

.PP
These symbolic addresses are recognized by this program and may be used instead of the actual address value.

.TP
.BR all
Equivalent to "broadcast", described next.

.TP
.BR broadcast
The Ethernet broadcast address, \fBFF:FF:FF:FF:FF:FF\fR.
All devices, whether local, remote or foreign will respond to this address.

.TP
.BR local
The Atheros Local Management Address (LMA), \fB00:B0:52:00:00:01\fR.
Local Atheros powerline devices recognize this address but remote and foreign powerline devices do not.
A remote device is any poserline device at the far end of the powerline.
A foreign device is a powerline device not manufactured by Atheros.

.SH REFERENCES
See the Qualcomm Atheros Firwmare Technical Reference Manual for more information about the MS_ADC_CAP management message.
See the Qualcomm Atheros PHY AFE Interface Functional Specification for more information for more information about the AFE and ADC capture.

.SH DISCLAIMER
Atheros HomePlug AV Vendor Specific Management Message structure and content is proprietary to Qualcomm Atheros, Ocala FL USA.
Consequently, public information is not available.
Qualcomm Atheros reserves the right to modify message structure or content in future firmware releases without any obligation to notify or compensate users of this program.

.SH EXAMPLES
The following command starts capture immediately because option \fB-n\fR is specified.
The gain is \fB10\fR because option \fB-g\fR is present.
Data capture takes several seconds.
Captured data is retained until it is collected or the device is reset.

.PP
   # adccap3 -n -g 10

.PP
The following command reads and displays captured data.
Displayed data is piped to file \fBadccap.log\fR.
No data is displayed if an error occurs.

.PP
   # adccap3 -r > adccap.log

.SH SEE ALSO
.BR adccap ( 1 ),
.BR adccap2 ( 1 ),
.BR plc ( 1 ),
.BR plctest ( 1 )

.SH CREDITS
 Charles Maier <cmaier@qca.qualcomm.com>

